# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AltUnity Headspin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HEADSPIN_TOKEN: ${{ secrets.HEADSPIN_TOKEN }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        curl https://api-dev.headspin.io/v0/releases/dl/cli/202205.85.0/linux/HeadSpin-CLI-v202205.85.0-x64.tar.gz -o HeadSpin-CLI-v202205.85.0-x64.tar.gz
        tar -xzvf HeadSpin-CLI-v202205.85.0-x64.tar.gz hs
        sudo mv hs /usr/local/bin
    - name: Test with behave
      run: |
        behave altunity_tester/features
