# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AltUnity SauceLabs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONFIG: "altunity_saucelabs"
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        curl https://saucelabs-vusb.s3.eu-west-1.amazonaws.com/v2.0.3/virtual-usb-client-2.0.3.jar -o virtual-usb-client.jar
    - name: Test with behave
      run: |
        export PATH=$PATH:/usr/local/lib/android/sdk/tools
        behave altunity_tester/features
      env:
        SAUCE_VUSB_JAR: "/home/runner/work/cucumber-python/cucumber-python/virtual-usb-client.jar"
